name: R CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: [ '4.1.3', 'release' ]  # 使用 4.1.3 和最新的稳定版

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      - name: Install system dependencies
        run: |
          brew install libgit2  # 解决 remotes 包的依赖问题
          brew install curl     # 可能需要 curl 进行 API 请求
          brew install openssl  # 一些 R 包依赖 OpenSSL
        shell: bash

      - name: Install R dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Check R package
        run: |
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
